### ISSUE TITLE
Doubt regarding implementation of SPADE normalization

### ISSUE THREAD

**Issue by rajatongit** [NVlabs/SPADE#104]
In the implementation, the SPADE is as follows:

![image](https://user-images.githubusercontent.com/22437185/74239299-dc8b0780-4cd7-11ea-8e69-392790e91025.png)

where we see an additional 1 is getting added. However, in the paper there is no additional term as can be visualized in this image from the paper:
![image](https://user-images.githubusercontent.com/22437185/74239532-515e4180-4cd8-11ea-9692-593fdd18756b.png)

My question is why is it [(1 + gamma) x normalization] and not just [gamma x normalization + beta]
Sorry if the doubt is too naive but I'm relatively new to this. Thank you! :)

**Comment by ahmed-fau** [comment]
You can remove the addition with 1 as mentioned by the author in issue [4](https://github.com/NVlabs/SPADE/issues/4).

**Comment by rajatongit** [comment]
@ahmed-fau Thank you for pointing out the solution. :) Didn't realize it was already answered. Duplicate of issue #4 so closing this.
