### ISSUE TITLE
Mismatch of Paper SPADE Equation and Code

### ISSUE THREAD

**Issue by mbbrodie** [NVlabs/SPADE#113]
Thanks for your great repo! 

Equation 1 of your paper (http://openaccess.thecvf.com/content_CVPR_2019/papers/Park_Semantic_Image_Synthesis_With_Spatially-Adaptive_Normalization_CVPR_2019_paper.pdf) shows: 

<img src="https://render.githubusercontent.com/render/math?math=\gamma^{i}_{c,y,x}(m) \frac{h^{i}_{n,c,y,x}-\mu^{i}_{c}}{\sigma^{i}_{c}} \texttt{+} \beta^{i}_{c,y,x}(m)">

(Sorry, Github isn't rendering the plus sign before \beta)

But line 108 in `models/networks/normalization.py` shows `out = normalized * (1 + gamma) + beta`.

Is there a reason for `normalized * (1 + gamma)`, rather than just `normalized * gamma`? 
Wouldn't that just shift the input?

https://github.com/NVlabs/SPADE/blob/1a687baeada266a3c92be41295f1ea3d5efd4f93/models/networks/normalization.py#L96-L110

**Comment by rajatongit** [comment]
May be a duplicate of #104 #4 issues. #4 contains an answer from contributors.

**Comment by mbbrodie** [comment]
Thanks @rajatongit ,  I didn't see #4 earlier but that answers my question.
