### ISSUE TITLE
--z_dim hard-coded in encoder 

### ISSUE THREAD

**Issue by kampelmuehler** [NVlabs/SPADE#139]
https://github.com/NVlabs/SPADE/blob/1a687baeada266a3c92be41295f1ea3d5efd4f93/models/networks/encoder.py#L32-L33

you have to change these 2 lines to

```  
 self.fc_mu = nn.Linear(ndf * 8 * s0 * s0, opt.z_dim)
 self.fc_var = nn.Linear(ndf * 8 * s0 * s0, opt.z_dim)
```

for the `--z_dim` option to take effect. Otherwise it will crash if you change the default (256).

**Comment by mingyuliutw** [comment]
# New implementation available at imaginaire repository

We have a reimplementation of the SPADE method that is more performant. It is avaiable at [Imaginaire](https://github.com/NVlabs/imaginaire)
