### ISSUE TITLE
Flickr Landscape Segmentation map

### ISSUE THREAD

**Issue by DezeZhao** [NVlabs/SPADE#143]
hello! could you tell how to use deeplab to make segmentation map for custom datasets. I have viewed many codes but that maybe give a clear guidance. I have scraw images from Flickr website,  do I just need to use the deeplab pre-training model to directly generate the corresponding semantic segmentation map from these images? Expect to get your reply, thank you!

**Comment by mingyuliutw** [comment]
# New implementation available at imaginaire repository

We have a reimplementation of the SPADE method that is more performant. It is avaiable at [Imaginaire](https://github.com/NVlabs/imaginaire)
