### ISSUE TITLE
Python test.py cannot be Successful opened

### ISSUE THREAD

**Issue by tociv05** [NVlabs/SPADE#144]
I have been doing all the Git installations. In the image can see the error. 
![image](https://user-images.githubusercontent.com/37695177/117545625-dabd0a80-b026-11eb-9fd7-2901e73522f9.png)

**Comment by ranch-hands** [comment]
hi
you shd first install the torch module.
try: 
pip install torch

**Comment by mingyuliutw** [comment]
# New implementation available at imaginaire repository

We have a reimplementation of the SPADE method that is more performant. It is avaiable at [Imaginaire](https://github.com/NVlabs/imaginaire)
