### ISSUE TITLE
How can I run this using RGB label as input ?

### ISSUE THREAD

**Issue by DWCTOD** [NVlabs/SPADE#149]
Thanks for  your great work!
I have try this project , but maybe the input label must be BW .Like this
![image](https://user-images.githubusercontent.com/41478810/127426852-e4125f8d-8c1e-4b64-b41b-c5d553ff1942.png)
So, I try to convert RGB label image to **grayscale**, and setup "label_nc"  very large,  it could success run.
If I want to input a RGB image as label, what should I do?

**Comment by ranch-hands** [comment]
hello dear @DWCTOD 
what do you mean by saying: setup "label_nc" very large?
I'm trying to do what you did. where did you find that RGB label? I mean was it in the datasets included in this spade project?

**Comment by mingyuliutw** [comment]
# New implementation available at imaginaire repository

We have a reimplementation of the SPADE method that is more performant. It is avaiable at [Imaginaire](https://github.com/NVlabs/imaginaire)

**Comment by DWCTOD** [comment]
> hello dear @DWCTOD
> what do you mean by saying: setup "label_nc" very large?
> I'm trying to do what you did. where did you find that RGB label? I mean was it in the datasets included in this spade project?

Hello, the dataset which I try to train is not in this spade project. And my dataset's label is different, so need to change setup a little.

**Comment by yja1** [comment]
want know how to train image to image: label is RGB image
