### ISSUE TITLE
module 'models.networks' has no attribute 'modify_commandline_options'

### ISSUE THREAD

**Issue by QiushiPan** [NVlabs/SPADE#16]
When I run "python test.py --name coco_pretrained --dataset_mode coco --dataroot H:\datasets\COCO\train"

Traceback (most recent call last):
  File "test.py", line 15, in <module>
    opt = TestOptions().parse()
  File "H:\SPADE-master\options\base_options.py", line 150, in parse
    opt = self.gather_options()
  File "H:\SPADE-master\options\base_options.py", line 85, in gather_options
    parser = model_option_setter(parser, self.isTrain)
  File "H:\SPADE-master\models\pix2pix_model.py", line 14, in modify_commandline_options
    networks.modify_commandline_options(parser, is_train)
AttributeError: module 'models.networks' has no attribute 'modify_commandline_options'

how can i fix that?thx

**Comment by myfunc** [comment]
I have the same problem.
How you fixed this?

**Comment by QiushiPan** [comment]
> I have the same problem.
> How you fixed this?

copy the whole 'sync_batchnorm' folder to the 'networks' folder, but not only replace the files.

**Comment by timhouben** [comment]
> > I have the same problem.
> > How you fixed this?
> 
> copy the whole 'sync_batchnorm' folder to the 'networks' folder, but not only replace the files.

This copy action is also mentioned in the installation procedure right?
cp Synchronized-BatchNorm-PyTorch/sync_batchnorm . -rf

Already did this but still get the AttributeError...

**Comment by QiushiPan** [comment]
> > > I have the same problem.
> > > How you fixed this?
> > 
> > 
> > copy the whole 'sync_batchnorm' folder to the 'networks' folder, but not only replace the files.
> 
> This copy action is also mentioned in the installation procedure right?
> cp Synchronized-BatchNorm-PyTorch/sync_batchnorm . -rf
> 
> Already did this but still get the AttributeError...

yes，it's already mentioned. have u fixed it？what's the whole error information?

**Comment by QiushiPan** [comment]
> > > I have the same problem.
> > > How you fixed this?
> > 
> > 
> > copy the whole 'sync_batchnorm' folder to the 'networks' folder, but not only replace the files.
> 
> This copy action is also mentioned in the installation procedure right?
> cp Synchronized-BatchNorm-PyTorch/sync_batchnorm . -rf
> 
> Already did this but still get the AttributeError...

yes，it's already mentioned. have u fixed it？what's the whole error information?

> > > I have the same problem.
> > > How you fixed this?
> > 
> > 
> > copy the whole 'sync_batchnorm' folder to the 'networks' folder, but not only replace the files.
> 
> This copy action is also mentioned in the installation procedure right?
> cp Synchronized-BatchNorm-PyTorch/sync_batchnorm . -rf
> 
> Already did this but still get the AttributeError...

yes，it's already mentioned. have u fixed it？what's the whole error information?

**Comment by mahesh557** [comment]
Any fix?

**Comment by potato123-hash** [comment]
any fix？

**Comment by peterkim333** [comment]
poor answer

**Comment by bimal-logix12** [comment]
Any Fix ?

**Comment by EriDeLee** [comment]
Ok I've got it. Just cp the whole sync_batchnorm folder to models\networks, not the files in it
