### ISSUE TITLE
What are the exact color values of pixels for each label?

### ISSUE THREAD

**Issue by code-de** [NVlabs/SPADE#18]
As I know now, each pixel of label/instance maps has a grayscale brightness value 0, 1, 2, ..., n, which corresponds to the object label.

I first thought that for COCO stuff dataset the values are simply these: https://github.com/nightrome/cocostuff/blob/master/labels.md

But it turns out to be a bit different. For example, to get a sky-other label (id 157 on the link above), the color of both label and instance maps pixels needs to be 163 for some reason. The same goes for the snow (159) - it's 165; and for sand (154) - 160.
But this +6 logic doesn't always work. For example, to get railroad (147), we seem to set pixel values to 154, which is +7 logic.

So the question is - how can we get the exact color values for each label?

Many thanks!

**Comment by strbean** [comment]
Seems to be buried in https://github.com/NVlabs/SPADE/blob/master/util/util.py

**Comment by taesungp** [comment]
Yes, also https://github.com/NVlabs/SPADE/blob/master/util/coco.py contains exact mappings. It is same as the link you provided (https://github.com/nightrome/cocostuff/blob/master/labels.md)?

**Comment by code-de** [comment]
Geez! Thank you guys. I figured it out: this works perfectly in any color picking/changing tools I tried except Photoshop CC. So strange that Photoshop gives me incorrect pixel brightness - that was the reason for this issue. Closing it now.
