### ISSUE TITLE
Add ETA to ReadME

### ISSUE THREAD

**Issue by S-B99** [NVlabs/SPADE#2]

**Comment by HoraceYork88** [comment]
Or just release it already

**Comment by javierbq** [comment]
https://media2.giphy.com/media/143vPc6b08locw/giphy.gif?cid=4bf119fc5c91361664716a2e511f981e

**Comment by Krystallus2** [comment]
My shitty MS Paint "art" really needs this.

**Comment by rIvM9TFnAWqLETZiB0raAnx0hGQJ7UYpOIFOLD9** [comment]
release it faggot

**Comment by msurguy** [comment]
@rIvM9TFnAWqLETZiB0raAnx0hGQJ7UYpOIFOLD9 please don't post comments like that, it doesn't help anybody.

**Comment by phongnhhn92** [comment]
From since when people start giving no manners in Github ? Please remove this unnecessary issue like this.

**Comment by smaximov** [comment]
@phongnhhn92 this issue is useful in a sense that people can subscribe to it and get notified on new comments and when the issue is closed/resolved. It's a shame that comments in such issues tend to be noise though.

**Comment by ImSpeakEnglish** [comment]
Hey, are there any updates on this? Or is still going to be released "very soon"?

**Comment by Alicetech** [comment]
@NVlabs Please give us an update. I'm willing to help with the release if you need it. Your release will help the open source community and is appreciated, regrdless of how unstable it might be.

**Comment by Kontorted** [comment]
Guys, stop pestering them to release the code quicker. Just be patient

**Comment by yazdan27** [comment]
i agree but 20 days isn't really "very soon" and i don't see why don't just release it

**Comment by baptisterajaut** [comment]
Hey guys calm down, they could have chosen NOT to release it. They do what
they want and don't owe you anything.

**Comment by ArashHosseini** [comment]
according to the publication, the experiments were conducted on NVIDIA DGX1 with 8 V100 GPUs, why is there such a big interest in the release of the experiment implementation? does not make the people any pressure, maybe they work on a light-version of the model

**Comment by HoraceYork88** [comment]
> i agree but 20 days isn't really "very soon" and i don't see why don't just release it

you are confusing soon with soon™, is not uncommon for people to get them confused.

**Comment by mingyuliutw** [comment]
Code is now released under CC BY-NC-SA for non-commercial use. For commercial usage, please contact `researchinquiries@nvidia.com`
