### ISSUE TITLE
running on gtx 10 series

### ISSUE THREAD

**Issue by claudetheboof** [NVlabs/SPADE#22]
is it possible for me to run this on GTX 1060 6gb? cuz I really just want to mess around with the neural stuff and learn from it.

**Comment by QiushiPan** [comment]
maybe u can test the code. it's too big to train on 1060.

**Comment by claudetheboof** [comment]
so youre saying that I can test the pretrained model but not able to physically train it ? welp testing it out is what I meant. thanks for the reply anyway. ima try it out rn

**Comment by taesungp** [comment]
I agree with @QiushiPan
