### ISSUE TITLE
why coco-stuff dataset?

### ISSUE THREAD

**Issue by ZQPei** [NVlabs/SPADE#23]
Hello,
COCO-Stuff dataset's segmentation map is labeled by machine, not human handwork and many of those annotations are pretty bad, especially on the boundary of seg-map.
It seems that the boundary of seg maps is quite important to SPADE.
SO Why use COCO-stuff dataset, rather than MS COCO?

**Comment by taesungp** [comment]
We needed a set of labels that are comprehensive enough to cover the background as well. MS COCO originally had only the labels of the foreground object. Without the labels of the background, we don't have semantic control of the background. COCO-Stuff seemed like the most comprehensive dataset with diversity.
