### ISSUE TITLE
why do 'label_image' * 255.0 ?

### ISSUE THREAD

**Issue by taki0112** [NVlabs/SPADE#28]
Hello
Thank you for sharing the code.
If you look at this [code](https://github.com/NVlabs/SPADE/blob/master/data/pix2pix_dataset.py#L63), you multiply the label image by `255.0`. What is the meaning?

For example, the maximum value of the label image in ADECallengeData2016 is 150. If you multiply it by 255, it will be `38250`...
no problem ?

**Comment by taesungp** [comment]
Just for record, it's because [`transforms.ToTensor()`](https://pytorch.org/docs/stable/torchvision/transforms.html#torchvision.transforms.ToTensor)  automatically scales the range of the image to [0.0, 1.0].
