### ISSUE TITLE
Segmentation image is always gray?

### ISSUE THREAD

**Issue by taki0112** [NVlabs/SPADE#29]
Hello
In [code](https://github.com/NVlabs/SPADE/blob/master/models/pix2pix_model.py#L123), you change the segmentation image to one-hot vector.

If segmentation images are gray, this process makes sense.

For example, if segmentation image shape = `[256, 256, 1]`, max pixel value = 150
then one-hot vector of segmap shape =`[256, 256, 1, 151]` and squeeze `[256, 256, 151]`
`last dimension = channel`

But if it's color, how do you turn it into a one-hot vector? I don't understand.
I think one-hot vector of segmap shape = `[256, 256, 3, 151]`..
Do I always have to prepare the segmentation image to Gray?

**Comment by taesungp** [comment]
If the semantic map is in color, you would first have to map the pixels values into class label numbers. 

For example, if red is `person`, you will have to first change the pixel value of `[255, 0, 0]` to the class label of `person`. 

As an alternative, if you don't have the class numbers that correspond to the RGB colors of the semantic layout, you can try modifying the code to directly learn meaningful feature embedding from the RGB values. In detail, you will comment out the code to create the one-hot vector and treat the 3-channel RGB values as input to SPADE. Our code currently does not support that.

**Comment by taki0112** [comment]
Did you try to insert the segmentation image instead of using one-hot vector? 
just do a simple normalization.

For example, if you have a segmentation image in the shape of [256, 256, 3],
Simply an attempt to a network with a value between -1 and 1.

**Comment by mingyuliutw** [comment]
Knowing that the labels are discrete value, fitting them in a continuous space of color values is likely sub-optimal.
