### ISSUE TITLE
Not able to process PTH files in checkpoints folder 

### ISSUE THREAD

**Issue by aeti-in** [NVlabs/SPADE#3]
python test.py --name coco_pretrained --dataset_mode coco --dataroot c:\spade\checkpoints\coco_pretrained
This ends with 
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    dataloader = data.create_dataloader(opt)
  File "c:\SPADE\data\__init__.py", line 44, in create_dataloader
    instance.initialize(opt)
  File "c:\SPADE\data\pix2pix_dataset.py", line 28, in initialize
    label_paths, image_paths, instance_paths = self.get_paths(opt)
  File "c:\SPADE\data\coco_dataset.py", line 34, in get_paths
    label_paths = make_dataset(label_dir, recursive=False, read_cache=True)
  File "c:\SPADE\data\image_folder.py", line 47, in make_dataset
    assert os.path.isdir(dir) or os.path.islink(dir), '%s is not a valid directory' % dir
AssertionError: .checkpoint\coco_pretrained\val_label is not a valid directory

Looks like site directory setting file is required?

I just realized that these PTH files are pytorch models. So I manually created empty missing folders and it ran but it created 0 byte image?? Something is missing please help.

**Comment by taesungp** [comment]
Hi aeti-in, 

`--dataroot` should be pointing to the dataset of input semantic layouts, not the pretrained model. For example, it can be ./datasets/coco_stuff. We put 8 images as examples there. To get more images, you will need to download from the coco-stuff dataset and specify `--dataroot` to the directory of your downloaded dataset.

**Comment by aeti-in** [comment]
Thanks, tarsungp.  Just a quick question, I am using this as a part of the academic update to our students so wondering if the GUI tool similar to one shown in the Youtube video is available or not. Thanks again in advance.

**Comment by mingyuliutw** [comment]
We cannot release the GUI tool through this repository, but we plan to release it using a different way. Likely people with recent NVIDIA GPUs will be able to run it.

**Comment by aeti-in** [comment]
Thanks, that will be great. I have Nvidia GEFORCE so I think hopefully it should be good enough.  Closing this thread now.
