### ISSUE TITLE
What is the "water-other" in coco-dataset

### ISSUE THREAD

**Issue by vincentgc** [NVlabs/SPADE#32]
I can only find the "water-other","waterdrops" in https://github.com/NVlabs/SPADE/blob/master/util/coco.py.

How can I reproduce the "water" in video demo? 

I cannot find the ‘sky’ too.

**Comment by taesungp** [comment]
They are actually `water-other` and `sky-other`. I dropped `-other` in the name to make them look more natural in the demo.
