### ISSUE TITLE
AssertionError: The label_path  and image_path  don't match.

### ISSUE THREAD

**Issue by bbminer** [NVlabs/SPADE#36]
python3 train.py --name coco_pretrained --dataset_mode coco --dataroot /home/python/Model_1/SPADE/datasets/coco_stuff/ --use_vae --gpu_ids -1  --no_pairing_check
----------------- Options ---------------
            D_steps_per_G: 1                             
             aspect_ratio: 1.0                           
                batchSize: 1                             
                    beta1: 0.5                           
                    beta2: 0.999                         
      cache_filelist_read: True                          
     cache_filelist_write: True                          
          checkpoints_dir: ./checkpoints                 
        coco_no_portraits: False                         
   contain_dontcare_label: True                          
           continue_train: False                         
                crop_size: 256                           
                 dataroot: /home/python/Model_1/SPADE/datasets/coco_stuff/      [default: ./datasets/cityscapes/]
             dataset_mode: coco                          
                    debug: False                         
             display_freq: 100                           
          display_winsize: 256                           
                 gan_mode: hinge                         
                  gpu_ids: -1                                   [default: 0]
                init_type: xavier                        
            init_variance: 0.02                          
                  isTrain: True                                 [default: None]
                 label_nc: 182                           
              lambda_feat: 10.0                          
               lambda_kld: 0.05                          
               lambda_vgg: 10.0                          
       load_from_opt_file: False                         
                load_size: 286                           
                       lr: 0.0002                        
         max_dataset_size: 9223372036854775807           
                    model: pix2pix                       
                 nThreads: 0                             
               n_layers_D: 3                             
                     name: coco_pretrained                      [default: label2coco]
                      ndf: 64                            
                      nef: 16                            
                     netD: multiscale                    
             netD_subarch: n_layer                       
                     netG: spade                         
                      ngf: 64                            
                    niter: 50                            
              niter_decay: 0                             
                  no_TTUR: False                         
                  no_flip: False                         
          no_ganFeat_loss: False                         
                  no_html: False                         
              no_instance: False                         
         no_pairing_check: True                                 [default: False]
              no_vgg_loss: False                         
                   norm_D: spectralinstance              
                   norm_E: spectralinstance              
                   norm_G: spectralspadesyncbatch3x3     
                    num_D: 2                             
    num_upsampling_layers: normal                        
                optimizer: adam                          
                output_nc: 3                             
                    phase: train                         
          preprocess_mode: resize_and_crop               
               print_freq: 100                           
          save_epoch_freq: 10                            
         save_latest_freq: 5000                          
           serial_batches: False                         
                   tf_log: False                         
                  use_vae: True                                 [default: False]
              which_epoch: latest                        
                    z_dim: 256                           
----------------- End -------------------
train.py --name coco_pretrained --dataset_mode coco --dataroot /home/python/Model_1/SPADE/datasets/coco_stuff/ --use_vae --gpu_ids -1 --no_pairing_check
dataset [CocoDataset] of size 118287 was created
Network [SPADEGenerator] was created. Total number of parameters: 112.6 million. To see the architecture, do print(network).
Network [MultiscaleDiscriminator] was created. Total number of parameters: 1.7 million. To see the architecture, do print(network).
Network [ConvEncoder] was created. Total number of parameters: 10.5 million. To see the architecture, do print(network).
create web directory ./checkpoints/coco_pretrained/web...
Traceback (most recent call last):
  File "train.py", line 34, in <module>
    for i, data_i in enumerate(dataloader, start=iter_counter.epoch_iter):
  File "/usr/local/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/usr/local/python3/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 615, in <listcomp>
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/home/python/Model_1/SPADE/data/pix2pix_dataset.py", line 70, in __getitem__
    (label_path, image_path)
AssertionError: The label_path /home/python/Model_1/SPADE/datasets/coco_stuff/train_label/000000008708.png and image_path /home/python/Model_1/SPADE/datasets/coco_stuff/train_img/000000012818.jpg don't match.

**Comment by taesungp** [comment]
Do the number and indices of filenames in 

/home/python/Model_1/SPADE/datasets/coco_stuff/train_label/
/home/python/Model_1/SPADE/datasets/coco_stuff/train_img/

match? For example, does 000000008708.png exist in /home/python/Model_1/SPADE/datasets/coco_stuff/train_img/?

**Comment by bbminer** [comment]
ok,the number of files is not same in the directory,I unzipped dataset again,this question is  solved,thanks
