### ISSUE TITLE
SPADE vs pix2pixHD on Faces datasets

### ISSUE THREAD

**Issue by mrvlasyuk** [NVlabs/SPADE#41]
Hi! Adding segmentation masks directly to intermediate layers is a great idea. Thanks for releasing the code.

I have noticed that in the paper you didn't show results of face generation tasks unlike in pix2pixHD paper. I'm working on the similar pet project, so I have a couple of questions. I would appreciate your insights 

Have you tried SPADE on faces datasets?
If yes: Is there significant improvement compared to pix2pixHD model?
If not: Why not? :)

**Comment by mingyuliutw** [comment]
@mrvlasyuk We did not try SPADE on face datasets.

**Comment by mrvlasyuk** [comment]
Any comments why not?

**Comment by ak9250** [comment]
this repo uses SPADE and funit https://github.com/shaoanlu/fewshot-face-translation-GAN
