### ISSUE TITLE
Image-to-image translation tasks

### ISSUE THREAD

**Issue by ChristianEschen** [NVlabs/SPADE#46]
Hi

Thanks for sharing this awesome code! I see that you have primary dealt with image-to-image translation tasks for inverse semantic segmentation. 
I am currious of why you have not tried any other image-to-image translation tasks. Is it possible to use the spade-network for day-2-night or summer-2-winther?

Best regards

**Comment by mingyuliutw** [comment]
This method is designed for supervised image to image translation setting where for each input image we have a target output image in the training dataset. It is difficult to collect such a dataset for Day2Night or Summer2Winter cases. You might want to look into methods like CycleGAN or UNIT for the task. SPADE module might be useful for boasting performance of those models too.
