### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'no_pairing_check'

### ISSUE THREAD

**Issue by AndroXD** [NVlabs/SPADE#6]
I tried COCO-stuff dataset and it worked flawlessly, but when I switch to Cityscapes dataset I get this error message.

```
Traceback (most recent call last):
  File "test.py", line 17, in <module>
    dataloader = data.create_dataloader(opt)
  File "C:\SPADE\data\__init__.py", line 44, in create_dataloader
    instance.initialize(opt)
  File "C:\SPADE\data\pix2pix_dataset.py", line 39, in initialize
    if not opt.no_pairing_check:
AttributeError: 'Namespace' object has no attribute 'no_pairing_check'
```

I downloaded "gtFine_trainvaltest.zip" and "leftImg8bit_trainvaltest.zip", unzipped in C:\SPADE\datasets\cityscapes , create C:\SPADE\results\cityscapes_pretrained folder
Then run: python test.py --name cityscapes_pretrained --dataset_mode cityscapes --dataroot C:\SPADE\datasets\cityscapes

If I disable lines 39 to 42 in C:\SPADE\data\pix2pix_dataset.py:

```
        if not opt.no_pairing_check:
            for path1, path2 in zip(label_paths, image_paths):
                assert self.paths_match(path1, path2), \
                    "The label-image pair (%s, %s) do not look like the right pair because the filenames are quite different. Are you sure about the pairing? Please see data/pix2pix_dataset.py to see what is going on, and use --no_pairing_check to bypass this." % (path1, path2)
```

It will generate images but I believe that's not an optimal solution.
Also, if I check the "gtFine_trainvaltest.zip" file I downloaded, inside "gtFine\test" folder, all pictures are 100% pitch black "#000000", is it normal?

Thank you for your kind attention.

**Comment by wasd96040501** [comment]
@AndroXD 
Oh, it seems a bug in Cityscapes dataset. 
Below is a part of code from cityscapes dataset.
https://github.com/NVlabs/SPADE/blob/a59ec99ec7ee9466fbb24dda1b3469cd66e5749a/data/cityscapes_dataset.py#L10-L14

Below is a part of code from ade20k dataset.
https://github.com/NVlabs/SPADE/blob/a59ec99ec7ee9466fbb24dda1b3469cd66e5749a/data/ade20k_dataset.py#L13-L18

Then you can find that there is a missing line in cityscapes dataset.
So, simply add a line to cityscapes dataset
```python
parser = Pix2pixDataset.modify_commandline_options(parser, is_train)
```
will fix that.

**Comment by taesungp** [comment]
@wasd96040501 thanks a lot! I pushed the fix.
