### ISSUE TITLE
How to use multiple GPUs?

### ISSUE THREAD

**Issue by joe1chief** [NVlabs/SPADE#69]
I have specified the 'gpu_ids' to "5, 6".
But the "nvidia-smi" reports the gpu 6 is idle. I have tested it multi-times.
<img width="559" alt="nv" src="https://user-images.githubusercontent.com/20919303/62346001-0b554380-b527-11e9-838d-5bbf6df612bb.png">

**Comment by Hshihua** [comment]
I have encountered such kind issue, have you found out what is going on?

**Comment by joe1chief** [comment]
> I have encountered such kind issue, have you found out what is going on?

After a restart, everything is fine.😢
