### ISSUE TITLE
--no_instance doesn't work

### ISSUE THREAD

**Issue by code-de** [NVlabs/SPADE#7]
When I'm trying to run test.py with --no_instance flag, I get the following error (I tried this flag on COCO and Cityscapes checkpoints, and the error happens on both):

`
Traceback (most recent call last):
  File "test.py", line 19, in <module>
    model = Pix2PixModel(opt)
  File "D:\...path...\SPADE\models\pix2pix_model.py", line 26, in __init__
    self.netG, self.netD, self.netE = self.initialize_networks(opt)
  File "D:\...path...\SPADE\models\pix2pix_model.py", line 98, in initialize_networks
    netG = util.load_network(netG, 'G', opt.which_epoch, opt)
  File "D:\...path...\SPADE\util\util.py", line 194, in load_network
    net.load_state_dict(weights)
  File "D:\...path...\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for SPADEGenerator:
        size mismatch for fc.weight: copying a param with shape torch.Size([1024, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([1024, 183, 3, 3]).
        size mismatch for head_0.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for head_0.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for G_middle_0.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for G_middle_0.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for G_middle_1.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for G_middle_1.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_0.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_0.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_0.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_1.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_1.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_1.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_2.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_2.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_2.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_3.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_3.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
        size mismatch for up_3.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).
`

**Comment by taesungp** [comment]
It is because the checkpoint model requires instance map. The number of input channel using instance map will be one larger than not using instance map. Please refer to [this issue](https://github.com/NVlabs/SPADE/issues/5#issuecomment-482721789)

**Comment by SaidaSaad** [comment]
> When I'm trying to run test.py with --no_instance flag, I get the following error (I tried this flag on COCO and Cityscapes checkpoints, and the error happens on both):
> 
> `Traceback (most recent call last): File "test.py", line 19, in <module> model = Pix2PixModel(opt) File "D:\...path...\SPADE\models\pix2pix_model.py", line 26, in __init__ self.netG, self.netD, self.netE = self.initialize_networks(opt) File "D:\...path...\SPADE\models\pix2pix_model.py", line 98, in initialize_networks netG = util.load_network(netG, 'G', opt.which_epoch, opt) File "D:\...path...\SPADE\util\util.py", line 194, in load_network net.load_state_dict(weights) File "D:\...path...\Python\Python36\lib\site-packages\torch\nn\modules\module.py", line 769, in load_state_dict self.__class__.__name__, "\n\t".join(error_msgs))) RuntimeError: Error(s) in loading state_dict for SPADEGenerator: size mismatch for fc.weight: copying a param with shape torch.Size([1024, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([1024, 183, 3, 3]). size mismatch for head_0.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for head_0.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for G_middle_0.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for G_middle_0.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for G_middle_1.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for G_middle_1.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_0.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_0.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_0.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_1.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_1.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_1.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_2.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_2.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_2.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_3.norm_0.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_3.norm_1.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]). size mismatch for up_3.norm_s.mlp_shared.0.weight: copying a param with shape torch.Size([128, 184, 3, 3]) from checkpoint, the shape in current model is torch.Size([128, 183, 3, 3]).`


Thank you for the code and the great work
I also got the same , I am using Input label maps (my own label maps but generated using model trained on COCO), Since instances maps is needed to use the pretrained model on coco stuff

I tried to use coco generated instance file to generated instances maps for them but i got the following error 
/mnt/HDD/VE_Saida/lib/python3.6/site-packages/skimage/io/_io.py:48: UserWarning: `as_grey` has been deprecated in favor of `as_gray`
  warn('`as_grey` has been deprecated in favor of `as_gray`')
Traceback (most recent call last):
  File "/mnt/HDD/VE_Saida/Updated_SPADE/SPADE-master/datasets/coco_generate_instance_map.py", line 54, in <module>
    img[rr, cc] = count
IndexError: index 256 is out of bounds for axis 0 with size 256

Process finished with exit code 1

Can you please let me know how can i use pre-trained mode for coco stuff on my lables maps dataset, I mean how i can generated instances for them .

Thank you very much

**Comment by SaidaSaad** [comment]
Hello @code-de  , did you solve this issue ?
